apiVersion: v1
kind: Service
metadata:
  name: matrix
spec:
  type: NodePort
  selector:
    run: matrix
  ports:
  - name: http
    targetPort: 8008
    port: 80
  - name: https
    targetPort: 8448
    port: 443
  - name: identd
    targetPort: 1113
    port: 113
    # nodePort: 113
  - name: turn
    port: 3478
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: matrix
spec:
  template:
    metadata:
      labels:
        run: matrix
    spec:
      initContainers:
        # Generate appservice-irc registration file
        - name: appservice-irc-registration
          image: tedomum/matrix-appservice-irc
          args: ["-r", "--file=/appservice-irc-config/irc_registration_file.yaml", "-u", "http://127.0.0.1:9999", "--config=/appservice-irc-config/config.yaml", "--localpart=my_bot"]
          volumeMounts:
            - name: appservice-irc-config
              mountPath: /appservice-irc-config
      containers:
        # Main matrix server
        - name: synapse
          image: ansiwen/matrix-synapse
          ports:
            - containerPort: 8008
              name: http
            - containerPort: 8448
              name: https
          volumeMounts:
            - name: synapse-config
              mountPath: /config
            - name: synapse-data
              mountPath: /data
            - name: riot-config
              mountPath: /riot/config
            - name: appservice-irc-config
              mountPath: /appservice-irc-config
        # IRC Bridge
        - name: appservice-irc
          image: tedomum/matrix-appservice-irc
          args: ["--file=/appservice-irc-config/irc_registration_file.yaml", "--config=/appservice-irc-config/config.yaml", "--port", "9999"]
          ports:
            - containerPort: 9999
            - containerPort: 1113
              hostPort: 113
              name: identd
          volumeMounts:
            - name: appservice-irc-config
              mountPath: /appservice-irc-config
            - name: appservice-irc-data
              mountPath: /appservice-irc-data
        # # TURN server
        # - name: coturn
        #   image: steppechange/docker-coturn
        #   ports:
        #     - containerPort: 3478
        #       protocol: TCP
        #     - containerPort: 3478
        #       protocol: UDP
        #     # also 30000-60000 udp
      volumes:
        - name: synapse-config
          hostPath:
            path: /hosthome/daurnimator/kubernetes-experiments/synapse-config
        - name: synapse-data
          hostPath:
            path: /tmp/synapse-data
        - name: riot-config
          hostPath:
            path: /hosthome/daurnimator/kubernetes-experiments/riot-config
        - name: appservice-irc-config
          hostPath:
            path: /hosthome/daurnimator/kubernetes-experiments/appservice-irc-config
        - name: appservice-irc-data
          hostPath:
            path: /tmp/appservice-irc-data
